config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :deal_groups
  resources :groups do
   resources :deals 
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "splash#index", as: :unauthenticated_root
  # root "users#index", as: :authenticated_root
end

app/models/deal_group.rb
class DealGroup < ApplicationRecord
  belongs_to :deal
  belongs_to :group

  validates :group_id, presence: true
  validates :deal_id, presence: true
end

app/controllers/deal_groups_controller.rb
class DealGroupsController < ApplicationController
  before_action :set_deal_group, only: %i[show edit update destroy]

  # GET /deal_groups or /deal_groups.json
  def index
    @deal_groups = DealGroup.all
  end

  # GET /deal_groups/1 or /deal_groups/1.json
  def show; end

  # GET /deal_groups/new
  def new
    @deal_group = DealGroup.new
  end

  # GET /deal_groups/1/edit
  def edit; end

  # def new_deal_group
  #   @deal_group = DealGroup.new
  #   # Set the title of the page
  #   @title = "New Deal Group"
  #   respond_to do |format|
  #     format.html do
  #       # Render the new deal form
  #       render :new
  #     end
  #   end
  # end

  # POST /deal_groups or /deal_groups.json
  def create
    @deal_group = DealGroup.new(deal_group_params)

    respond_to do |format|
      if @deal_group.save
        format.html { redirect_to deal_group_url(@deal_group), notice: 'Deal group was successfully created.' }
        format.json { render :show, status: :created, location: @deal_group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @deal_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /deal_groups/1 or /deal_groups/1.json
  def update
    respond_to do |format|
      if @deal_group.update(deal_group_params)
        format.html { redirect_to deal_group_url(@deal_group), notice: 'Deal group was successfully updated.' }
        format.json { render :show, status: :ok, location: @deal_group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @deal_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /deal_groups/1 or /deal_groups/1.json
  def destroy
    @deal_group.destroy

    respond_to do |format|
      format.html { redirect_to deal_groups_url, notice: 'Deal group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deal_group
    @deal_group = DealGroup.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def deal_group_params
    params.require(:deal_group).permit(:deal_id, :group_id)
  end
end

app/helpers/deal_groups_helper.rb
module DealGroupsHelper
end

app/views/deal_groups/_deal_group.html.erb
<div id="<%= dom_id deal_group %>">
  <p>
    <strong>Deal:</strong>
    <%= deal_group.deal_id %>
  </p>

  <p>
    <strong>Group:</strong>
    <%= deal_group.group_id %>
  </p>

</div>

app/views/deal_groups/_form.html.erb
<%= form_with model: @deal_group do |form| %>
  <% if deal_group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(deal_group.errors.count, "error") %> prohibited this deal_group from being saved:</h2>

      <ul>
        <% deal_group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :deal_id, style: "display: block" %>
    <%= form.text_field :deal_id %>
  </div>

  <div>
    <%= form.label :group_id, style: "display: block" %>
    <%= form.text_field :group_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/deal_groups/edit.html.erb
<h1>Editing deal group</h1>

<%= render "form", deal_group: @deal_group %>

<br>

<div>
  <%= link_to "Show this deal group", @deal_group %> |
  <%= link_to "Back to deal groups", deal_groups_path %>
</div>

app/views/deal_groups/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Deal groups</h1>

<div id="deal_groups">
  <% @deal_groups.each do |deal_group| %>
    <%= render deal_group %>
    <p>
      <%= link_to "Show this deal group", deal_group %>
    </p>
  <% end %>
</div>

<%= link_to "New deal group", new_deal_group_path %>

app/views/deal_groups/new.html.erb
<h1>NEW DEAL</h1>

<%= render "form", deal_group: @deal_group %>

<br>

<div>
  <%= link_to "Back to deal groups", deal_groups_path %>
</div>

app/views/deal_groups/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @deal_group %>

<div>
  <%= link_to "Edit this deal group", edit_deal_group_path(@deal_group) %> |
  <%= link_to "Back to deal groups", deal_groups_path %>

  <%= button_to "Destroy this deal group", @deal_group, method: :delete %>
</div>