config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :deal_groups
  resources :groups do
   resources :deals 
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "splash#index", as: :unauthenticated_root
  # root "users#index", as: :authenticated_root
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user, class_name: 'User'

  has_one_attached :icon
  has_many :deal_groups, dependent: :destroy, class_name: 'DealGroup'
  has_many :deals, through: :deal_group

  validates :name, presence: true
  validates :icon, presence: true

  def calculate_amount
    deals.sum { |deal| deal.amount.to_i }
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %i[show edit update destroy]
  before_action :authenticate_user!

  # GET /groups or /groups.json
  def index
    @groups = Group.all
    @deals = Deal.all
    # @groups = Group.includes(:deals).where(user: current_user)
  end

  # GET /groups/1 or /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups or /groups.json
  def create
    name = params[:name]
    icon = params[:icon]
    p name
    p icon
    @group = Group.new(group_params)
    puts current_user.id
    @group.user = current_user

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
        format.json { render :show, status: :created, location: @group }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1 or /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to group_url(@group), notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1 or /groups/1.json
  def destroy
    @group.destroy

    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:name, :icon, :user_id)
  end
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(group.errors.count, "error") %> prohibited this group from being saved:</h2>

      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form_field">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class="form_field">
    <%= form.label :icon, style: "display: block" %>
    <%= form.file_field :icon %>
  </div>

  <div class="form_field_button">
    <%= form.submit %>
  </div>
<% end %>

app/views/groups/_group.html.erb
<div class="info_card" id="<%= dom_id group %>">
<p><%= image_tag group.icon, class: 'category_icon' %></p>
 <div id="info"> 
 <p>
    <%= link_to(group.name, group_deals_path(group.id), class: 'category_name') %>
  </p>
   <p><%= group.created_at.strftime("%d %b %Y")%></p>
</div>
<p>$<%= @deals.sum {|deal| deal.amount} %></p>
</div>

app/views/groups/edit.html.erb
<h1>Editing group</h1>

<%= render "form", group: @group %>

<br>

<div>
  <%= link_to "Show this group", @group %> |
  <%= link_to "Back to groups", groups_path %>
</div>

app/views/groups/index.html.erb
<%= render partial: 'shared/header_bar', locals: {title:'CATEGORY', symbol:':::', url: :back}%>

<div id="groups">
    <% @groups.each do |group| %>
    <% if can? :read, group %>
      <%= render partial: 'group', locals: { group: group } %>
    <% end %>
  <% end %>
</div>

<div class="card-button"><button><%= link_to "Add new category", new_group_path %></button></div>

app/views/groups/new.html.erb
<div class="details-header">
 <p >
    <%= link_to '←', groups_path, class: 'arrow-link' %>
</p>
<h2>New Category</h2>
</div>

<%= render "form", group: @group %>

<br>

app/views/groups/show.html.erb
<%# <%= render @group %>
<div class="details-header">
 <p >
    <%= link_to '←',groups_path, class: 'arrow-link' %>
</p>
<h2>Details</h2>
</div>
<div class="details">
<div id="details_info">
<p><%= image_tag @group.icon, class: 'category_icon' %></p>
<h3 class='category_name'><%= @group.name %></h3>
</div>
<hr>
<p id="date"><%= @group.created_at%></p>
<hr>
<div id="amount">
<p>Total Payment</p>
<p>$200</p>
</div>
</div>
<div>
  
  <%= link_to "Add new deal", new_group_deal_path(group_id: @group.id) %>
</div>