config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :deal_groups
  resources :groups do
   resources :deals 
  end
  resources :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "splash#index", as: :unauthenticated_root
  # root "users#index", as: :authenticated_root
end

app/models/deal.rb
class Deal < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :deal_group, dependent: :destroy
  has_many :groups, through: :destroy

  validates :name, presence: true
  validates :amount, numericality: { is_decimal: true }
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :set_deal, only: %i[show edit update destroy]

  # GET /deals or /deals.json
  def index
    @deals = Deal.all
  end

  # GET /deals/new
  def new
    @group = Group.find(params[:group_id])
    @deal = Deal.new
  end

  # POST /deals or /deals.json
  def create
    @deal = Deal.new(deal_params)
    @group = Group.find(params[:group_id])
    if @deal.save
      DealGroup.create(group_id: @group.id, deal_id: @deal.id)
      flash[:notice] = 'Deal was successfully created.'
      redirect_to group_deals_path(@group)
    else
      flash[:alert] = 'Deal could not be created.'
      render :new
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_deal
    @deal = Deal.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def deal_params
    params.require(:deal).permit(:name, :amount).merge(author: current_user)
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_deal.html.erb
<div class= "info_card"  id="<%= dom_id deal %>">
 <div class="name">
        <p>  
          <%= deal.name %>
        </p>
        <small class='text-secondary'>
          <%= deal.created_at.strftime("%d %h %Y")%> at <%=deal.created_at.strftime("%l.%M%P")%>
        </small>
      </div>
  <p>
    $<%= deal.amount %>
  </p>

</div>

app/views/deals/_form.html.erb
<%= form_with model: @deal, url: group_deals_path(controller: :deals, action: :create, group_id: @group.id), method: :post do |form| %>
<% if deal.errors.any? %>
<div style="color: red">
<h2><%= pluralize(deal.errors.count, "error") %> prohibited this deal from being saved:</h2>
<ul>
<% deal.errors.each do |error| %>
<li><%= error.full_message %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="form_field">
<%= form.label :name, style: "display: block" %>
<%= form.text_field :name, required: true %>
</div>
<div class="form_field">
<%= form.label :amount, style: "display: block" %>
<%= form.text_field :amount, required: true %>
</div>
<div  class="form_field">
<%= form.label :group, style: "display: block" %>
<%= form.collection_select :group_id, Group.all, :id, :name, { include_blank: 'Select Group', selected: @group.id }, required: true %>
</div>
<div class="form_field_button">
<%= form.submit %>
</div>
<% end %>

app/views/deals/edit.html.erb
<h1>Editing deal</h1>

<%= render "form", deal: @deal %>

<br>

<div>
  <%= link_to "Show this deal", @deal %> |
  <%= link_to "Back to deals", deals_path %>
</div>

app/views/deals/index.html.erb
<div class="details-header">
 <p >
    <%= link_to '←',groups_path, class: 'arrow-link' %>
</p>
<h2>Deals</h2>
</div>
<div class="total_box">
<p>
<span>Total payment:</span>
</p>
<span class='font-weight-bold'>$<%= @deals.sum {|deal| deal.amount} %></span>
</div>
<div id="deals">
  <% @deals.each do |deal| %>
    <%= render deal %>
  <% end %>
</div>

<div class="card-button"><button><%= link_to "New deal", new_group_deal_path %></button></div>

app/views/deals/new.html.erb
<div class="details-header">
 <p >
    <%= link_to '←',group_deals_path, class: 'arrow-link' %>
</p>
<h2>New Deal</h2>
</div>
<%= render "form", deal: @deal %>

app/views/deals/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @deal %>

<div>
  <%= link_to "Edit this deal", edit_deal_path(@deal) %> |
  <%= link_to "Back to deals", deals_path %>

  <%= button_to "Destroy this deal", @deal, method: :delete %>
</div>